kind: pipeline
name: default
steps:
  - name: test
    image: openjdk
    image: maven
    commands:
      - cd wordladder
      - mvn test
    when: 
      event: push
  - name: build
    image: openjdk
    image: maven
    commands:
      - cd wordladder
      - mvn clean package
    when:
      event: push
  - name: build-gateway
    image: openjdk
    imgae: maven
    commands:
     - cd Gateway
     - mvn test
     - mvn build
     when: 
      event: push