server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/llIllIllIlllIll/SpringCloudConfig
          clone-on-start: true
  application:
    name: configserver
security:
  user:
    password: 666666

