server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/llIllIllIlllIll/CloudNativePractice.git
          clone-on-start: true
security:
  user:
    password: 666666